# Generated by Django 3.0.5 on 2021-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverable_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
