# Generated by Django 3.0.5 on 2021-04-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_part', models.CharField(choices=[('L', 'Leaf'), ('S', 'Stem'), ('F', 'Fruit'), ('W', 'Whole Plant')], max_length=1)),
                ('desease_name', models.CharField(max_length=50)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.crop')),
            ],
        ),
    ]
