# Generated by Django 3.0.5 on 2021-04-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('info', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
