# Generated by Django 3.0.5 on 2021-04-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.TextField(),
        ),
    ]
