# Generated by Django 3.0.5 on 2021-04-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AandAdd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(blank=True, max_length=20)),
                ('account_no', models.IntegerField(default=0)),
                ('passbook_no', models.IntegerField(default=0)),
                ('IFSC', models.CharField(max_length=15, null=True)),
                ('account_type', models.CharField(max_length=10, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sold_by', models.CharField(max_length=30)),
                ('farmer_id', models.IntegerField(default=0)),
                ('crop_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('suspend', models.BooleanField(default=False)),
                ('quantity_in_kg', models.IntegerField()),
                ('quantity_bought', models.IntegerField(default=0)),
                ('remaing_quantity', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('price_per_kg', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('amount', models.IntegerField(default=0)),
                ('total_rating', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
            ],
        ),
    ]
